{
  imports = [
    ./audio.nix
    ./brightness.nix
    ./bluetooth.nix
    ./boot.nix
    ./docker.nix
    ./env.nix
    ./flatpak.nix
    ./graphics.nix
    ./home-manager.nix
    ./hyprland.nix
    ./kernel.nix
    ./mime.nix
    ./net.nix
    ./nh.nix
    ./niri.nix
    ./nix.nix
    ./timezone.nix
    ./user.nix
    ./zram.nix
  ];
}
